config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :apps

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  root 'welcome#index'
end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy


end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :app
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

  skip_before_action :verify_authenticity_token

  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    app = App.find_by(url: request.env['HTTP_ORIGIN'])

    if app
      @event = app.events.build(event_params)
      if @event.save
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
    @apps = App.all
  end

  def show
    @app = App.find(params[:id])
    @events = @app.events.group_by(&:name)
  end

  def new
    @app = App.new
  end

  def create
    @app = App.new
    @app.name = params[:app][:name]
    @app.url = params[:app][:url]
    @app.user = current_user

    if @app.save
      flash[:notice] = "Success"
      redirect_to apps_path
    else
      flash.now[:alert] = "Fail!"
      render :new
    end
  end

  def edit
    @app = App.find(params[:id])
  end


  def update
    @app = App.find(params[:id])
    @app.name = params[:app][:name]
    @app.url = params[:app][:url]
    @app.user = current_user

    if @app.save
      flash[:notice] = "Success"
      redirect_to apps_path
    else
      flash.now[:alert] = "Fail!"
      render :new
    end
  end

  def destroy
    @app = App.find(params[:id])

    if @app.destroy
      flash[:notice] = "Success"
      redirect_to apps_path
    else
      flash.now[:alert] = "Fail!"
      render :show
    end

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/edit.html.erb
<%= params %>
<h1>New Application</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>No Porn</li>
      <li>No Dodgers</li>
      <li>No Lakers</li>
    </ul>
  </div>
  <div class="col-md-6">
    <%= form_for @app do |f| %>

      <div class="form_group" >
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form form-control' %>
      </div >

      <div class="form_group" >
        <%= f.label :url %>
        <%= f.text_area :url, class: 'form form-control' %>
      </div>
      <br>
      <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-success' %>
      </div>

    <% end %>
  </div>
</div>

app/views/apps/index.html.erb
<h1>Applications</h1>

<% @apps.each do |app| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to app.name, app_path(app) %>
      </h4>
      <%= link_to "Edit", edit_app_path(app) %> |
      <%= link_to "Delete", app, method: :delete %>
    </div>
  </div>

<% end %>

app/views/apps/new.html.erb
<%= params %>
<h1>New Application</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>No Porn</li>
      <li>No Dodgers</li>
      <li>No Lakers</li>
    </ul>
  </div>
  <div class="col-md-6">
    <%= form_for @app do |f| %>

      <div class="form_group" >
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form form-control' %>
      </div >

      <div class="form_group" >
        <%= f.label :url %>
        <%= f.text_area :url, class: 'form form-control' %>
      </div>
      <br>
      <div class="form-group">
        <%= f.submit "Submit", class: 'btn btn-success' %>
      </div>

    <% end %>
  </div>
</div>

app/views/apps/show.html.erb
<h1><%= @app.name %></h1>

<%= pie_chart @app.events.group(:name).count %>

<%= line_chart @app.events.group_by_day(:created_at).count %>

<ul>
<% @events.each do |event| %>
  <li><%= event[0] %>: <%= event[1].size %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div>
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocmetrics", root_path %></li>
      <li><%= link_to "Applications", apps_path %></li>
      <li><%= link_to "New App", new_app_path %></li>


      <div class="pull-right user-info">
        <% if user_signed_in? %>
            <div class='glyphicon glyphicon-user lt_blue'></div>
            <%= current_user.email %> |
          <%= link_to 'My Account', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Log In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>


    </div>

          <% if flash[:notice] %>
    				<div class="alert alert-success">
    					<button type="button" class="close" data-dismiss="alert">&times;</button>
    					<%= flash[:notice] %>
    				</div>
    			<% elsif flash[:error] %>
    				<div class="alert alert-danger">
    					<button type="button" class="close" data-dismiss="alert">&times;</button>
    					<%= flash[:error] %>
    				</div>
    			<% elsif flash[:alert] %>
    				<div class="alert alert-warning">
    					<button type="button" class="close" data-dismiss="alert">&times;</button>
    					<%= flash[:alert] %>
    				</div>
    			<% end %>




      <%= yield %>
    </div>
</body>
</html>

app/views/welcome/index.html.erb
        <div class="jumbotron">
          <h1>Blocmetrics</h1>
          <p>Analyze and report user activity on your web app</p>
          <p>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
          </p>
        </div>
      </div>
    </div>